<?php
 return array (
  'connect' => 'connect(host : string, [port : int], [timeout : int = 1]):bool',
  'addserver' => 'addserver(host : string, [port : int = 11211], [persistent : bool = true], [weight : int|null = null], [timeout : int = 1], [retry_interval : int = 15], [status : bool = true], [failure_callback : callable = null], [timeoutms : int]):bool',
  'setserverparams' => 'setServerParams(host : string, [port : int = 11211], [timeout : int = 1], [retry_interval : int = 15], [status : bool = true], [failure_callback : callable]):bool',
  'setfailurecallback' => 'setFailureCallback():void',
  'getserverstatus' => 'getserverstatus(host : string, [port : int = 11211]):int',
  'findserver' => 'findserver():void',
  'getversion' => 'getversion():bool|string',
  'add' => 'add(key : string, var, [flag : int], [expire : int]):array|bool',
  'set' => 'set(key : string, var, [flag : int], [expire : int]):bool',
  'replace' => 'replace(key : string, var, [flag : int], [expire : int]):bool',
  'cas' => 'cas():void',
  'append' => 'append():void',
  'prepend' => 'prepend():string',
  'get' => 'get(key : array|string, [&flags : array|int]):array|string',
  'delete' => 'delete(key : string, [timeout : int = 0]):bool',
  'getstats' => 'getstats([type : string], [slabid : int], [limit : int = 100]):array|bool',
  'getextendedstats' => 'getextendedstats([type : string], [slabid : int], [limit : int = 100]):array|bool',
  'setcompressthreshold' => 'setCompressThreshold(thresold : int, [min_saving : float = 0.2]):bool',
  'increment' => 'increment(key : string, [value : int = 1]):bool',
  'decrement' => 'decrement(key : string, [value : int = 1]):int',
  'close' => 'close():bool',
  'flush' => 'flush():bool',
  'pconnect' => 'pconnect(host : string, [port : int], [timeout : int = 1]):mixed',
);