<?php
 return array (
  'connect' => 'connect(host : string, [port : int = 6379], [timeout : float = 0.0]):bool',
  'psetex' => 'psetex(key : string, ttl : int, value : string):bool',
  'sScan' => 'sScan(key : string, iterator : int, [pattern : string = \'\'], [count : int = 0]):array|bool',
  'scan' => 'scan(iterator : int, [pattern : string = \'\'], [count : int = 0]):array|bool',
  'zScan' => 'zScan(key : string, iterator : int, [pattern : string = \'\'], [count : int = 0]):array|bool',
  'hScan' => 'hScan(key : string, iterator : int, [pattern : string = \'\'], [count : int = 0]):array',
  'client' => 'client(command : string, [arg : string = \'\']):mixed',
  'slowlog' => 'slowlog(command : string):mixed',
  'open' => 'open(host : string, [port : int = 6379], [timeout : float = 0.0]):void',
  'pconnect' => 'pconnect(host : string, [port : int = 6379], [timeout : float = 0.0]):bool',
  'popen' => 'popen(host : string, [port : int = 6379], [timeout : float = 0.0]):void',
  'close' => 'close():void',
  'setOption' => 'setOption(name : string, value : string):bool',
  'getOption' => 'getOption(name : string):int',
  'ping' => 'ping():string',
  'get' => 'get(key : string):bool|string',
  'set' => 'set(key : string, value : string, [timeout : int = 0]):bool',
  'setex' => 'setex(key : string, ttl : int, value : string):bool',
  'setnx' => 'setnx(key : string, value : string):bool',
  'del' => 'del(key1 : array|int, [key2 = null], [key3 = null]):int',
  'delete' => 'delete(key1, [key2 = null], [key3 = null]):void',
  'multi' => 'multi():Redis',
  'exec' => 'exec():void',
  'discard' => 'discard():void',
  'watch' => 'watch(key : array|string):void',
  'unwatch' => 'unwatch():void',
  'subscribe' => 'subscribe(channels : array, callback : array|string):void',
  'psubscribe' => 'psubscribe(patterns : array, callback : array|string):void',
  'publish' => 'publish(channel : string, message : string):int',
  'exists' => 'exists(key : string):bool',
  'incr' => 'incr(key : string):int',
  'incrByFloat' => 'incrByFloat(key : string, increment : float):float',
  'incrBy' => 'incrBy(key : string, value : int):int',
  'decr' => 'decr(key : string):int',
  'decrBy' => 'decrBy(key : string, value : int):int',
  'getMultiple' => 'getMultiple(keys : array):array',
  'lPush' => 'lPush(key : string, value1 : string, [value2 = null], [valueN = null]):int',
  'rPush' => 'rPush(key : string, value1 : string, [value2 = null], [valueN = null]):int',
  'lPushx' => 'lPushx(key : string, value : string):int',
  'rPushx' => 'rPushx(key : string, value : string):int',
  'lPop' => 'lPop(key : string):string',
  'rPop' => 'rPop(key : string):string',
  'blPop' => 'blPop(keys : array):array',
  'brPop' => 'brPop(keys : array):array',
  'lLen' => 'lLen(key : string):int',
  'lSize' => 'lSize(key : string):void',
  'lIndex' => 'lIndex(key : string, index : int):String',
  'lGet' => 'lGet(key : string, index : int):void',
  'lSet' => 'lSet(key : string, index : int, value : string):BOOL',
  'lRange' => 'lRange(key : string, start : int, end : int):array',
  'lGetRange' => 'lGetRange(key : string, start : int, end : int):void',
  'lTrim' => 'lTrim(key : string, start : int, stop : int):array',
  'listTrim' => 'listTrim(key : string, start : int, stop : int):void',
  'lRem' => 'lRem(key : string, value : string, count : int):int',
  'lRemove' => 'lRemove(key : string, value : string, count : int):void',
  'lInsert' => 'lInsert(key : string, position : int, pivot : string, value : string):int',
  'sAdd' => 'sAdd(key : string, value1 : string, [value2 = null], [valueN = null]):int',
  'sRem' => 'sRem(key : string, member1 : string, [member2 = null], [memberN = null]):int',
  'sRemove' => 'sRemove(key : string, member1 : string, [member2 = null], [memberN = null]):void',
  'sMove' => 'sMove(srcKey : string, dstKey : string, member : string):bool',
  'sIsMember' => 'sIsMember(key : string, value : string):bool',
  'sContains' => 'sContains(key : string, value : string):void',
  'sCard' => 'sCard(key : string):int',
  'sPop' => 'sPop(key : string):string',
  'sRandMember' => 'sRandMember(key : string):string',
  'sInter' => 'sInter(key1 : string, key2 : string, [keyN = null]):array',
  'sInterStore' => 'sInterStore(dstKey : string, key1 : string, key2 : string, [keyN = null]):int',
  'sUnion' => 'sUnion(key1 : string, key2 : string, [keyN = null]):array',
  'sUnionStore' => 'sUnionStore(dstKey : string, key1 : string, key2 : string, [keyN = null]):int',
  'sDiff' => 'sDiff(key1 : string, key2 : string, [keyN = null]):array',
  'sDiffStore' => 'sDiffStore(dstKey : string, key1 : string, key2 : string, [keyN = null]):int',
  'sMembers' => 'sMembers(key : string):array',
  'sGetMembers' => 'sGetMembers(key : string):void',
  'getSet' => 'getSet(key : string, value : string):string',
  'randomKey' => 'randomKey():string',
  'select' => 'select(dbindex : int):bool',
  'move' => 'move(key : string, dbindex : int):bool',
  'rename' => 'rename(srcKey : string, dstKey : string):bool',
  'renameKey' => 'renameKey(srcKey : string, dstKey : string):void',
  'renameNx' => 'renameNx(srcKey : string, dstKey : string):bool',
  'expire' => 'expire(key : string, ttl : int):bool',
  'pExpire' => 'pExpire(key : string, ttl):bool',
  'setTimeout' => 'setTimeout(key : string, ttl : int):void',
  'expireAt' => 'expireAt(key : string, timestamp : int):bool',
  'pExpireAt' => 'pExpireAt(key : string, timestamp : int):bool',
  'keys' => 'keys(pattern : string):array',
  'getKeys' => 'getKeys(pattern : string):void',
  'dbSize' => 'dbSize():int',
  'auth' => 'auth(password : string):bool',
  'bgrewriteaof' => 'bgrewriteaof():bool',
  'slaveof' => 'slaveof([host : string = \'127.0.0.1\'], [port : int = 6379]):bool',
  'object' => 'object([string : string = \'\'], [key : string = \'\']):string',
  'save' => 'save():bool',
  'bgsave' => 'bgsave():bool',
  'lastSave' => 'lastSave():int',
  'type' => 'type(key : string):int',
  'append' => 'append(key : string, value : string):int',
  'getRange' => 'getRange(key : string, start : int, end : int):string',
  'substr' => 'substr(key : string, start : int, end : int):void',
  'setRange' => 'setRange(key : string, offset : int, value : string):string',
  'strlen' => 'strlen(key : string):int',
  'getBit' => 'getBit(key : string, offset : int):int',
  'setBit' => 'setBit(key : string, offset : int, value : bool|int):int',
  'bitCount' => 'bitCount(key : string):int',
  'bitOp' => 'bitOp(operation : string, retKey : string, key1 : string, key2 : string, [key3 = null]):int',
  'flushDB' => 'flushDB():bool',
  'flushAll' => 'flushAll():bool',
  'sort' => 'sort(key : string, [option : array|null = null]):array',
  'info' => 'info([option = null]):string',
  'resetStat' => 'resetStat():bool',
  'ttl' => 'ttl(key : string):int',
  'pttl' => 'pttl(key : string):int',
  'persist' => 'persist(key : string):bool',
  'mset' => 'mset(array : array):bool',
  'mget' => 'mget(array : array):array',
  'msetnx' => 'msetnx(array : array):int',
  'rpoplpush' => 'rpoplpush(srcKey : string, dstKey : string):string',
  'brpoplpush' => 'brpoplpush(srcKey : string, dstKey : string, timeout : int):string',
  'zAdd' => 'zAdd(key : string, score1 : float, value1 : string, [score2 : float|null = null], [value2 = null], [scoreN : float|null = null], [valueN = null]):int',
  'zRange' => 'zRange(key : string, start : int, end : int, [withscores : bool|null = null]):array',
  'zRem' => 'zRem(key : string, member1 : string, [member2 = null], [memberN = null]):int',
  'zDelete' => 'zDelete(key : string, member1 : string, [member2 = null], [memberN = null]):int',
  'zRevRange' => 'zRevRange(key : string, start : int, end : int, [withscore : bool|null = null]):array',
  'zRangeByScore' => 'zRangeByScore(key : string, start : int, end : int, [options : array = array()]):array',
  'zRevRangeByScore' => 'zRevRangeByScore(key : string, start : int, end : int, [options : array = array()]):array',
  'zCount' => 'zCount(key : string, start : string, end : string):int',
  'zRemRangeByScore' => 'zRemRangeByScore(key : string, start : float|string, end : float|string):int',
  'zDeleteRangeByScore' => 'zDeleteRangeByScore(key : string, start : float, end : float):void',
  'zRemRangeByRank' => 'zRemRangeByRank(key : string, start : int, end : int):int',
  'zDeleteRangeByRank' => 'zDeleteRangeByRank(key : string, start : int, end : int):void',
  'zCard' => 'zCard(key : string):int',
  'zSize' => 'zSize(key : string):void',
  'zScore' => 'zScore(key : string, member : string):float',
  'zRank' => 'zRank(key : string, member : string):int',
  'zRevRank' => 'zRevRank(key : string, member : string):int',
  'zIncrBy' => 'zIncrBy(key : string, value : float, member : string):float',
  'zUnion' => 'zUnion(Output : string, ZSetKeys : array, [Weights : array = null], [aggregateFunction : string = \'SUM\']):int',
  'zInter' => 'zInter(Output : string, ZSetKeys : array, [Weights : array = null], [aggregateFunction : string = \'SUM\']):int',
  'hSet' => 'hSet(key : string, hashKey : string, value : string):int',
  'hSetNx' => 'hSetNx(key : string, hashKey : string, value : string):bool',
  'hGet' => 'hGet(key : string, hashKey : string):string',
  'hLen' => 'hLen(key : string):int',
  'hDel' => 'hDel(key : string, hashKey1 : string, [hashKey2 = null], [hashKeyN = null]):int',
  'hKeys' => 'hKeys(key : string):array',
  'hVals' => 'hVals(key : string):array',
  'hGetAll' => 'hGetAll(key : string):array',
  'hExists' => 'hExists(key : string, hashKey : string):bool',
  'hIncrBy' => 'hIncrBy(key : string, hashKey : string, value : int):int',
  'hIncrByFloat' => 'hIncrByFloat(key : string, field : string, increment : float):float',
  'hMset' => 'hMset(key : string, hashKeys : array):bool',
  'hMGet' => 'hMGet(key : string, hashKeys : array):array',
  'config' => 'config(operation : string, key : string, [value : string]):array',
  'evaluate' => 'evaluate(script : string, [args : array = array()], [numKeys : int = 0]):void',
  'evalSha' => 'evalSha(scriptSha : string, [args : array = array()], [numKeys : int = 0]):mixed',
  'evaluateSha' => 'evaluateSha(scriptSha : string, [args : array = array()], [numKeys : int = 0]):void',
  'script' => 'script(command : string, script : string):mixed',
  'getLastError' => 'getLastError():string',
  'clearLastError' => 'clearLastError():bool',
  '_prefix' => '_prefix(value : \\The):string',
  '_unserialize' => '_unserialize(value : string):mixed',
  'dump' => 'dump(key : string):string',
  'restore' => 'restore(key : string, ttl : int, value : string):bool',
  'migrate' => 'migrate(host : string, port : int, key : string, db : int, timeout : int):bool',
  'time' => 'time():array',
  'echo' => 'echo()',
  'eval' => 'eval(script : string, [args : array = array()], [numKeys : int = 0])',
);